<a href="https://colab.research.google.com/github/fralfaro/MA_M3/blob/main/semana_02/sc_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/960px-NumPy_logo_2020.svg.png?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20251223090330" width = "300" align="center"/>

> *"NumPy es al cómputo científico en Python lo que el álgebra lineal
> es a las matemáticas: el lenguaje base sobre el que todo lo demás se construye."*


## Introducción

[NumPy](https://numpy.org/) es la biblioteca fundamental para el cómputo numérico en Python. Su objeto central — el **array multidimensional** (`ndarray`) —  permite operar sobre vectores y matrices de forma eficiente, con una sintaxis mucho más limpia que las listas nativas de Python.

En este módulo aprenderás a:

- Crear y manipular arrays de una y múltiples dimensiones
- Realizar operaciones aritméticas, estadísticas y de álgebra lineal
- Visualizar datos numéricos con **matplotlib** de forma básica


## Python Lists vs Numpy Arrays

Antes de crear arrays, vale la pena entender por qué no basta con las listas de Python.

Una lista de Python no guarda directamente los números dentro del bloque principal de la lista. Guarda **referencias** a objetos, y cada entero es un objeto separado en memoria.

Una forma aproximada de pensarlo, para una lista `lst` con `n` enteros, es:

```python
memoria_lista ≈ tamaño_base_lista + n * tamaño_referencia + n * tamaño_entero
```

En una máquina de 64 bits suele verse algo como:

```python
56 + 8 * len(lst) + 28 * len(lst)
```

> Los valores exactos pueden cambiar según la versión de Python, el sistema operativo y la arquitectura. Por eso es mejor medir con `sys.getsizeof` cuando necesitamos un número concreto.


<img src="https://raw.githubusercontent.com/fralfaro/MAT281_2022/main/docs/lectures/data_manipulation/scientific_computing/images/list_structure.png" width = "500" align="center"/>

> Listas

En cambio, un array de NumPy guarda los datos numéricos en un bloque contiguo de memoria. Para un array de `n` enteros de 64 bits (`int64`), la parte de datos ocupa aproximadamente:

```python
n * 8 bytes
```

Además existe un costo fijo del objeto `ndarray`, que depende del entorno. La idea importante es que NumPy evita crear un objeto Python independiente por cada número.


<img src="https://raw.githubusercontent.com/fralfaro/MAT281_2022/main/docs/lectures/data_manipulation/scientific_computing/images/array_structure.png" width = "500" align="center"/>

> Numpy arrays

In [86]:
import numpy as np 
import time
import sys

def arreglo_python(n):
    t1 = time.time()
    X = range(n)
    Y = range(n)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return (time.time() - t1,sys.getsizeof(Z) )

def arreglo_numpy(n):
    t1 = time.time()
    X = np.arange(n)
    Y = np.arange(n)
    Z = X + Y
    return (time.time() - t1,sys.getsizeof(Z) )

In [87]:
# generar varios casos
for size_of_vec in [10,100,1000,10000,100000,1000000]:
    print(f"size of vector: {size_of_vec}")
    
    #list vs numpy
    t1, size1 = arreglo_python(size_of_vec)
    t2, size2 = arreglo_numpy(size_of_vec)
    
    # resultados
    print(f"python list -- time: {round(t1,8)} seg, size: {size1} bytes")
    print(f"numpy array -- time: {round(t2,8)} seg, size: {size2} bytes\n")

size of vector: 10
python list -- time: 8.11e-06 seg, size: 184 bytes
numpy array -- time: 0.00010586 seg, size: 192 bytes

size of vector: 100
python list -- time: 1.073e-05 seg, size: 920 bytes
numpy array -- time: 1.621e-05 seg, size: 912 bytes

size of vector: 1000
python list -- time: 0.00018835 seg, size: 8856 bytes
numpy array -- time: 1.788e-05 seg, size: 8112 bytes

size of vector: 10000
python list -- time: 0.00109911 seg, size: 85176 bytes
numpy array -- time: 0.00061297 seg, size: 80112 bytes

size of vector: 100000
python list -- time: 0.01199007 seg, size: 800984 bytes
numpy array -- time: 0.00106311 seg, size: 800112 bytes

size of vector: 1000000
python list -- time: 0.10486269 seg, size: 8448728 bytes
numpy array -- time: 0.00556135 seg, size: 8000112 bytes



> ✅ NumPy es ~2x más eficiente en memoria y hasta **50x más rápido**, para operaciones numéricas a gran escala.

## Objetos en Numpy

<img src="https://miro.medium.com/v2/resize:fit:1400/1*X0Dg7QfSYtWhSAu-afi8-g.png" width = "400" align="center"/>


El objeto principal es el `ndarray`. Puede ser 1D (vector), 2D (matriz) o nD (tensor).


In [88]:
import numpy as np

# Vector (1D)
v = np.array([1, 2, 3])

# Matriz (2D)
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Tensor (3D)
T = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(f"vector: shape={v.shape}, ndim={v.ndim}, dtype={v.dtype}")
print(f"matriz: shape={M.shape}, ndim={M.ndim}, dtype={M.dtype}")
print(f"tensor: shape={T.shape}, ndim={T.ndim}, dtype={T.dtype}")

vector: shape=(3,), ndim=1, dtype=int64
matriz: shape=(2, 3), ndim=2, dtype=int64
tensor: shape=(2, 2, 2), ndim=3, dtype=int64


| Atributo     | Descripción                              | Ejemplo         |
|--------------|------------------------------------------|-----------------|
| `.shape`     | Dimensiones del array                    | `(3,)`, `(2,3)` |
| `.ndim`      | Número de dimensiones                    | `1`, `2`, `3`   |
| `.size`      | Total de elementos                       | `6`             |
| `.dtype`     | Tipo de datos                            | `int64`, `float64` |

### Arrays especiales

NumPy incluye funciones para crear arrays comunes sin escribir todos sus elementos a mano. Esto es útil para inicializar datos, preparar matrices auxiliares o construir secuencias numéricas.

Las funciones más usadas en esta etapa son:

| Función | ¿Qué crea? | Uso típico |
|---|---|---|
| `np.zeros(shape)` | arreglo lleno de ceros | inicializar resultados o contadores |
| `np.ones(shape)` | arreglo lleno de unos | crear bases, máscaras simples o valores iniciales |
| `np.eye(n)` | matriz identidad $n \times n$ | álgebra de matrices |
| `np.arange(inicio, fin, paso)` | secuencia con paso fijo | índices, rangos enteros o discretos |
| `np.linspace(inicio, fin, n)` | `n` puntos igualmente espaciados | grillas, gráficos y simulaciones |
| `np.random.uniform(a, b, size)` | números aleatorios entre `a` y `b` | ejemplos, simulaciones y pruebas |

> En `shape`, una dimensión se escribe como tupla: `(filas, columnas)`. Por ejemplo, `(3, 3)` significa 3 filas y 3 columnas.


#### `np.zeros`: arrays llenos de ceros

`np.zeros` crea un array donde todos los elementos parten en cero. Es muy común usarlo cuando queremos guardar resultados que se van calculando después.


In [89]:
import numpy as np

ceros = np.zeros((3, 3))
print("zeros (3x3):")
print(ceros)


zeros (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### `np.ones`: arrays llenos de unos

`np.ones` crea un array donde todos los elementos valen uno. Sirve como punto de partida cuando necesitamos una matriz base o cuando todos los casos comienzan con el mismo valor.


In [90]:
import numpy as np

unos = np.ones((2, 4))
print("ones (2x4):")
print(unos)


ones (2x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### `np.eye`: matriz identidad

`np.eye(n)` crea la matriz identidad de tamaño $n \times n$: unos en la diagonal principal y ceros en el resto.

La matriz identidad funciona como el número 1 en multiplicación matricial: si las dimensiones calzan, multiplicar por ella no cambia la matriz.


In [91]:
import numpy as np

I = np.eye(3)
print("identidad (3x3):")
print(I)


identidad (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### `np.arange`: secuencias con paso fijo

`np.arange(inicio, fin, paso)` crea valores desde `inicio` hasta antes de `fin`, avanzando de `paso` en `paso`.

Es parecido a `range` de Python, pero devuelve un array de NumPy.


In [92]:
import numpy as np

secuencia = np.arange(0, 10, 2)
print("arange (0 a 10, paso 2):")
print(secuencia)


arange (0 a 10, paso 2):
[0 2 4 6 8]


#### `np.linspace`: puntos igualmente espaciados

`np.linspace(inicio, fin, n)` crea exactamente `n` valores entre `inicio` y `fin`, incluyendo ambos extremos.

Es especialmente útil para gráficos, porque permite construir una grilla regular de puntos.


In [93]:
import numpy as np

puntos = np.linspace(0, 1, 5)
print("linspace (0 a 1, 5 puntos):")
print(puntos)


linspace (0 a 1, 5 puntos):
[0.   0.25 0.5  0.75 1.  ]


#### Números aleatorios y `seed`

`np.random.uniform(a, b, size)` genera números aleatorios entre `a` y `b`.

La línea `np.random.seed(42)` fija la semilla aleatoria. Esto hace que el ejemplo sea reproducible: cada vez que ejecutamos la celda, aparecen los mismos números.


In [94]:
import numpy as np

np.random.seed(42)
aleatorios = np.random.uniform(0, 10, size=6)

print("uniform aleatorio (seed=42):")
print(aleatorios)


uniform aleatorio (seed=42):
[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452 ]


#### Mini ejemplo: inicializar y llenar resultados

Una forma típica de usar `zeros` es crear un arreglo vacío de resultados y luego ir llenándolo con cálculos.


In [95]:
import numpy as np

ventas = np.array([120, 80, 150, 100])
precio = 2500

ingresos = np.zeros(ventas.shape)
for i in range(len(ventas)):
    ingresos[i] = ventas[i] * precio

print("ventas:")
print(ventas)
print("ingresos:")
print(ingresos)


ventas:
[120  80 150 100]
ingresos:
[300000. 200000. 375000. 250000.]


## Vectores

### Definición

Un **vector** de dimensión $n$ es una lista ordenada de $n$ números reales. El conjunto de todos ellos se denota $\mathbb{R}^n$:

$$
\mathbf{v} \;=\;
\begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix} \in \mathbb{R}^{n},
\qquad v_i \in \mathbb{R}
$$

- $v_i$ es la **componente** $i$-ésima del vector.
- Por convención, un vector es un **vector columna** (orden $n \times 1$).
- Su transpuesta $\mathbf{v}^{T} = [\,v_1\; v_2\; \cdots\; v_n\,]$ es un **vector fila** (orden $1 \times n$).

> ⚠️ En NumPy un vector 1D tiene `shape = (n,)`: **no es fila ni columna**, es simplemente un arreglo de $n$ elementos. Cuando la distinción importa (por ejemplo, en un producto matricial) hay que forzar la forma con `reshape`.

In [96]:
import numpy as np

v = np.array([1, 2, 3])          # vector "plano" de NumPy

columna = v.reshape(-1, 1)       # 3 x 1  -> vector columna matemático
fila = v.reshape(1, -1)          # 1 x 3  -> vector fila matemático

print(f"v        -> shape={v.shape}       ndim={v.ndim}")
print(v)
print(f"\ncolumna  -> shape={columna.shape}    ndim={columna.ndim}")
print(columna)
print(f"\nfila     -> shape={fila.shape}    ndim={fila.ndim}")
print(fila)

# componentes: la matematica indexa desde 1, NumPy desde 0
print(f"\nv_1 = {v[0]},  v_2 = {v[1]},  v_3 = {v[2]}")
print(f"dimension n = {v.size}")

v        -> shape=(3,)       ndim=1
[1 2 3]

columna  -> shape=(3, 1)    ndim=2
[[1]
 [2]
 [3]]

fila     -> shape=(1, 3)    ndim=2
[[1 2 3]]

v_1 = 1,  v_2 = 2,  v_3 = 3
dimension n = 3


### Suma y producto por escalar

Dados $\mathbf{u}, \mathbf{v} \in \mathbb{R}^n$ y $\alpha \in \mathbb{R}$, ambas operaciones se definen **componente a componente**:

$$
(\mathbf{u} + \mathbf{v})_i = u_i + v_i
\qquad\qquad
(\alpha\,\mathbf{v})_i = \alpha\, v_i
$$

En datos reales, estas operaciones aparecen todo el tiempo:

- **Inventario:** sumar stock de dos bodegas producto por producto.
- **Presupuesto:** multiplicar todos los gastos por un factor, por ejemplo subirlos en 10%.
- **Puntajes:** combinar notas o indicadores con distintos pesos.

Una **combinación lineal** es una suma ponderada de vectores:

$$
\alpha_1\mathbf{v}_1 + \alpha_2\mathbf{v}_2 + \cdots + \alpha_k\mathbf{v}_k
$$

La idea práctica es simple: cada vector aporta una parte y los escalares indican cuánto pesa esa parte.


In [97]:
import numpy as np

# Stock de tres productos en dos bodegas: [notebooks, monitores, teclados]
bodega_a = np.array([12, 7, 20])
bodega_b = np.array([5, 9, 14])

stock_total = bodega_a + bodega_b
stock_con_10_por_ciento_extra = 1.10 * stock_total

print(f"stock total: {stock_total}")
print(f"stock con 10% extra: {np.round(stock_con_10_por_ciento_extra, 1)}")

# Puntaje final como suma ponderada: 40% prueba, 60% proyecto
prueba = np.array([6.0, 4.8, 5.5, 6.4])
proyecto = np.array([6.5, 5.9, 6.0, 6.8])
final = 0.4 * prueba + 0.6 * proyecto

print(f"notas finales: {np.round(final, 2)}")


stock total: [17 16 34]
stock con 10% extra: [18.7 17.6 37.4]
notas finales: [6.3  5.46 5.8  6.64]


### Producto punto y norma

El **producto punto** de dos vectores del mismo largo entrega un **número**:

$$
\mathbf{u} \cdot \mathbf{v} = \sum_{i=1}^{n} u_i v_i
$$

Una lectura útil es: multiplicar pares de valores y luego sumar. Por eso sirve para fórmulas como:

- **Total de compra:** cantidades $\cdot$ precios.
- **Promedio ponderado:** valores $\cdot$ pesos.
- **Puntaje de un modelo simple:** características $\cdot$ pesos.

La **norma** mide el tamaño o magnitud de un vector:

$$
\|\mathbf{v}\|_2 = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}
$$

> En NumPy `u * v` multiplica elemento a elemento; `u @ v` o `np.dot(u, v)` calcula el producto punto.


In [98]:
import numpy as np

# Total de una compra: cantidades por precios unitarios
cantidades = np.array([2, 1, 3])          # pan, leche, fruta
precios = np.array([1200, 950, 700])      # pesos por unidad

total = cantidades @ precios
print(f"total compra: ${total}")

# Promedio ponderado de notas
notas = np.array([5.8, 6.2, 4.9])
pesos = np.array([0.30, 0.30, 0.40])
print(f"promedio ponderado: {notas @ pesos:.2f}")

# Magnitud de un desplazamiento: 3 cuadras al este y 4 al norte
desplazamiento = np.array([3, 4])
print(f"distancia aproximada: {np.linalg.norm(desplazamiento):.1f} cuadras")


total compra: $5450
promedio ponderado: 5.56
distancia aproximada: 5.0 cuadras


## Matrices

### Definición

Una **matriz** $A$ de orden $m \times n$ es un arreglo rectangular de $m$ **filas** y $n$ **columnas**:

$$
A = (a_{ij}) =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} \in \mathbb{R}^{m \times n}
$$

donde $a_{ij}$ es el elemento de la **fila $i$** y la **columna $j$**.

- Si $m = n$ la matriz es **cuadrada** de orden $n$.
- Un vector columna es el caso $n = 1$; un vector fila, el caso $m = 1$.
- Una matriz sirve para guardar datos tabulares: filas como casos y columnas como variables.

> En matemáticas los índices parten en $1$ ($a_{11}$ es la esquina superior izquierda); en NumPy parten en $0$. Es decir, $a_{ij}$ corresponde a `A[i-1, j-1]`.


In [99]:
import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])

m, n = A.shape
print(f"A es una matriz de orden {m} x {n}  ({A.size} elementos, dtype={A.dtype})")
print(A)

print(f"\na_11 = A[0, 0] = {A[0, 0]}")
print(f"a_23 = A[1, 2] = {A[1, 2]}     (fila 2, columna 3)")
print(f"a_34 = A[2, 3] = {A[2, 3]}")

print(f"\nfila 2      A[1, :] = {A[1, :]}")
print(f"columna 3   A[:, 2] = {A[:, 2]}")

print("\ntranspuesta A^T (orden {} x {}):".format(n, m))
print(A.T)

A es una matriz de orden 3 x 4  (12 elementos, dtype=int64)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

a_11 = A[0, 0] = 1
a_23 = A[1, 2] = 7     (fila 2, columna 3)
a_34 = A[2, 3] = 12

fila 2      A[1, :] = [5 6 7 8]
columna 3   A[:, 2] = [ 3  7 11]

transpuesta A^T (orden 4 x 3):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Suma, producto por escalar y transpuesta

Para $A, B \in \mathbb{R}^{m\times n}$ y $\alpha \in \mathbb{R}$, la suma y el producto por escalar son **componente a componente** (ambas matrices deben tener el **mismo orden**):

$$
(A+B)_{ij} = a_{ij} + b_{ij}
\qquad\qquad
(\alpha A)_{ij} = \alpha\, a_{ij}
$$

La **transpuesta** $A^{T} \in \mathbb{R}^{n \times m}$ intercambia filas por columnas:

$$
(A^{T})_{ij} = a_{ji}
$$

**Propiedades:**

| Propiedad | Expresión |
|---|---|
| Conmutatividad de la suma | $A + B = B + A$ |
| Asociatividad de la suma | $(A+B)+C = A+(B+C)$ |
| Matriz nula (neutro) | $A + O = A$ |
| Doble transpuesta | $(A^{T})^{T} = A$ |
| Transpuesta de la suma | $(A+B)^{T} = A^{T} + B^{T}$ |
| Transpuesta del escalar | $(\alpha A)^{T} = \alpha A^{T}$ |
| Transpuesta del producto | $(AB)^{T} = B^{T} A^{T}$ &nbsp;&nbsp; ⚠️ *se invierte el orden* |

In [100]:
import numpy as np

A = np.array([[1., 2.], [3., 4.], [5., 6.]])     # 3 x 2
B = np.array([[7., 8.], [9., 10.], [11., 12.]])  # 3 x 2
C = np.array([[0., 1.], [1., 0.], [2., 2.]])     # 3 x 2
alpha = 2.5

print("A + B =")
print(A + B)
print(f"\n{alpha} * A =")
print(alpha * A)

print("\n--- propiedades ---")
print(f"conmutativa       A+B == B+A            : {np.allclose(A + B, B + A)}")
print(f"asociativa        (A+B)+C == A+(B+C)    : {np.allclose((A + B) + C, A + (B + C))}")
print(f"matriz nula       A+O == A              : {np.allclose(A + np.zeros_like(A), A)}")
print(f"doble transpuesta (A^T)^T == A          : {np.allclose(A.T.T, A)}")
print(f"transp. suma      (A+B)^T == A^T+B^T    : {np.allclose((A + B).T, A.T + B.T)}")
print(f"transp. escalar   (aA)^T == a A^T       : {np.allclose((alpha * A).T, alpha * A.T)}")

# transpuesta de un producto: se invierte el orden
D = np.array([[1., 0., 2.], [3., 1., 1.]])       # 2 x 3
print(f"transp. producto  (AD)^T == D^T A^T     : {np.allclose((A @ D).T, D.T @ A.T)}")
print(f"\nel orden importa: (AD)^T tiene shape {(A @ D).T.shape}, "
      f"pero A^T D^T tiene shape {(A.T @ D.T).shape} -> ni siquiera son comparables")

A + B =
[[ 8. 10.]
 [12. 14.]
 [16. 18.]]

2.5 * A =
[[ 2.5  5. ]
 [ 7.5 10. ]
 [12.5 15. ]]

--- propiedades ---
conmutativa       A+B == B+A            : True
asociativa        (A+B)+C == A+(B+C)    : True
matriz nula       A+O == A              : True
doble transpuesta (A^T)^T == A          : True
transp. suma      (A+B)^T == A^T+B^T    : True
transp. escalar   (aA)^T == a A^T       : True
transp. producto  (AD)^T == D^T A^T     : True

el orden importa: (AD)^T tiene shape (3, 3), pero A^T D^T tiene shape (2, 2) -> ni siquiera son comparables


### Producto matricial

El producto matricial permite combinar tablas de números de forma ordenada. Si $A \in \mathbb{R}^{m\times n}$ y $B \in \mathbb{R}^{n\times p}$, entonces $C = AB \in \mathbb{R}^{m\times p}$ y:

$$
c_{ij} = \sum_{k=1}^{n} a_{ik}\, b_{kj}
$$

Es decir, cada elemento de $C$ sale de multiplicar una fila de $A$ por una columna de $B$ y sumar.

**Regla de dimensiones:** las dimensiones internas deben coincidir:

$$
(m \times \boxed{n}) \cdot (\boxed{n} \times p) = (m \times p)
$$

Ejemplos típicos:

- Ventas por producto $\times$ precios por producto = ingreso total.
- Cantidades compradas por cliente $\times$ tabla de precios = total por cliente.
- Horas trabajadas por tarea $\times$ costo por hora = costo de proyecto.

> `A * B` es elemento a elemento; `A @ B` es producto matricial.


In [101]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])          # 2 x 3
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])           # 3 x 2

print(f"A: {A.shape}   B: {B.shape}   ->  AB: ({A.shape[0]}, {B.shape[1]})")
print("\nAB =")
print(A @ B)

# --- calculo manual con la definicion c_ij = sum_k a_ik b_kj ---
m, n = A.shape
_, p = B.shape
C = np.zeros((m, p), dtype=int)
for i in range(m):
    for j in range(p):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

print("\nmismo resultado con la definicion (triple bucle):")
print(C)
print(f"coinciden: {np.array_equal(C, A @ B)}")

# c_ij como producto punto fila_i . columna_j
print(f"\nc_12 = fila 1 de A . columna 2 de B = {A[0, :]} . {B[:, 1]} = {A[0, :] @ B[:, 1]}")

# --- error tipico: dimensiones incompatibles ---
try:
    A @ A
except ValueError as e:
    print(f"\nA @ A falla porque (2x3)(2x3): {e}")

A: (2, 3)   B: (3, 2)   ->  AB: (2, 2)

AB =
[[ 58  64]
 [139 154]]

mismo resultado con la definicion (triple bucle):
[[ 58  64]
 [139 154]]
coinciden: True

c_12 = fila 1 de A . columna 2 de B = [1 2 3] . [ 8 10 12] = 64

A @ A falla porque (2x3)(2x3): matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


#### Ejemplo: ventas, precios y totales

Supongamos que cada fila representa una sucursal y cada columna un producto. Si multiplicamos la matriz de cantidades por el vector de precios, obtenemos el ingreso total de cada sucursal.


In [102]:
import numpy as np

# Filas: sucursales. Columnas: cafe, te, jugo
ventas = np.array([
    [30, 12, 18],
    [22, 15, 10],
    [28, 10, 25],
])

precios = np.array([1800, 1200, 1500])
ingresos = ventas @ precios

print(f"ingresos por sucursal: {ingresos}")
print(f"ingreso total: ${ingresos.sum()}")


ingresos por sucursal: [95400 72600 99900]
ingreso total: $267900


#### Ejemplo: recetas como matriz

Una matriz también puede representar ingredientes por receta. Al multiplicarla por el precio de cada ingrediente, obtenemos el costo de preparar cada receta.


In [103]:
import numpy as np

# Columnas: harina, huevos, leche
recetas = np.array([
    [2.0, 3.0, 1.0],   # panqueques
    [1.5, 2.0, 0.5],   # queque
    [0.5, 4.0, 0.2],   # omelette
])

precio_ingredientes = np.array([900, 250, 1100])
costo_recetas = recetas @ precio_ingredientes

print(f"costos por receta: {costo_recetas}")
print(f"receta mas barata: {np.argmin(costo_recetas)}")


costos por receta: [3650. 2400. 1670.]
receta mas barata: 2


In [104]:
import numpy as np

A = np.array([[1., 2.], [3., 4.]])
B = np.array([[0., 1.], [1., 0.]])
C = np.array([[2., 0.], [1., 3.]])
I = np.eye(2)
alpha = 3.0

print("--- propiedades que SI se cumplen ---")
print(f"asociativa       (AB)C == A(BC)        : {np.allclose((A @ B) @ C, A @ (B @ C))}")
print(f"distributiva izq A(B+C) == AB+AC       : {np.allclose(A @ (B + C), A @ B + A @ C)}")
print(f"distributiva der (A+B)C == AC+BC       : {np.allclose((A + B) @ C, A @ C + B @ C)}")
print(f"escalares        a(AB) == (aA)B        : {np.allclose(alpha * (A @ B), (alpha * A) @ B)}")
print(f"identidad        AI == IA == A         : {np.allclose(A @ I, A) and np.allclose(I @ A, A)}")
print(f"transpuesta      (AB)^T == B^T A^T     : {np.allclose((A @ B).T, B.T @ A.T)}")

print("\n--- propiedades que NO se cumplen ---")
print("AB =");  print(A @ B)
print("BA =");  print(B @ A)
print(f"AB == BA : {np.allclose(A @ B, B @ A)}   -> el producto NO es conmutativo")

# AB = 0 sin que A ni B sean nulas
P = np.array([[1., 1.], [1., 1.]])
Q = np.array([[1., -1.], [-1., 1.]])
print("\nP @ Q =")
print(P @ Q)
print("...pero ni P ni Q son la matriz nula -> no hay 'divisores de cero' triviales")

# AB = AC sin que B = C
S = np.array([[1., 1.], [1., 1.]])
X = np.array([[1., 2.], [3., 4.]])
Y = np.array([[2., 3.], [2., 3.]])
print(f"\nSX == SY : {np.allclose(S @ X, S @ Y)}  pero  X == Y : {np.allclose(X, Y)}"
      "   -> no se puede 'cancelar' S")

--- propiedades que SI se cumplen ---
asociativa       (AB)C == A(BC)        : True
distributiva izq A(B+C) == AB+AC       : True
distributiva der (A+B)C == AC+BC       : True
escalares        a(AB) == (aA)B        : True
identidad        AI == IA == A         : True
transpuesta      (AB)^T == B^T A^T     : True

--- propiedades que NO se cumplen ---
AB =
[[2. 1.]
 [4. 3.]]
BA =
[[3. 4.]
 [1. 2.]]
AB == BA : False   -> el producto NO es conmutativo

P @ Q =
[[0. 0.]
 [0. 0.]]
...pero ni P ni Q son la matriz nula -> no hay 'divisores de cero' triviales

SX == SY : True  pero  X == Y : False   -> no se puede 'cancelar' S


### Matrices especiales

| Tipo | Definición | En NumPy |
|---|---|---|
| **Cuadrada** | $m = n$ | `A.shape[0] == A.shape[1]` |
| **Nula** | $a_{ij}=0\;\forall i,j$ | `np.zeros((m, n))` |
| **Identidad** | $I_{ij} = 1$ si $i=j$, $0$ si no | `np.eye(n)` |
| **Diagonal** | $a_{ij}=0$ para $i \neq j$ | `np.diag(v)` |
| **Triangular superior** | $a_{ij}=0$ para $i > j$ | `np.triu(A)` |
| **Triangular inferior** | $a_{ij}=0$ para $i < j$ | `np.tril(A)` |
| **Simétrica** | $A = A^{T}$ | `np.allclose(A, A.T)` |

**Hechos útiles:**

- La matriz identidad funciona como el número 1 en el producto matricial: `A @ I = A`.
- Una matriz diagonal es útil cuando cada variable se multiplica por su propio factor.
- Las matrices triangulares aparecen al resolver sistemas de ecuaciones de manera eficiente.


In [105]:
import numpy as np

np.random.seed(0)
A = np.random.randint(0, 5, size=(3, 3)).astype(float)
print("matriz A:")
print(A)

print("\ntriangular superior np.triu(A):")
print(np.triu(A))
print("\ntriangular inferior np.tril(A):")
print(np.tril(A))
print("\ndiagonal np.diag([1, 2, 3]):")
print(np.diag([1., 2., 3.]))
print(f"\ndiagonal de A: {np.diag(A)}")

I = np.eye(3)
D = np.diag([10., 100., 1000.])
v = np.array([1., 2., 3.])

print("\nidentidad I:")
print(I)
print(f"A @ I == A : {np.allclose(A @ I, A)}")

print("\nmatriz diagonal D:")
print(D)
print(f"D @ v multiplica cada componente por su factor: {D @ v}")

S = 0.5 * (A + A.T)
print("\nejemplo de matriz simetrica construida desde A:")
print(S)
print(f"S == S.T : {np.allclose(S, S.T)}")


matriz A:
[[4. 0. 3.]
 [3. 3. 1.]
 [3. 2. 4.]]

triangular superior np.triu(A):
[[4. 0. 3.]
 [0. 3. 1.]
 [0. 0. 4.]]

triangular inferior np.tril(A):
[[4. 0. 0.]
 [3. 3. 0.]
 [3. 2. 4.]]

diagonal np.diag([1, 2, 3]):
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]

diagonal de A: [4. 3. 4.]

identidad I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A @ I == A : True

matriz diagonal D:
[[  10.    0.    0.]
 [   0.  100.    0.]
 [   0.    0. 1000.]]
D @ v multiplica cada componente por su factor: [  10.  200. 3000.]

ejemplo de matriz simetrica construida desde A:
[[4.  1.5 3. ]
 [1.5 3.  1.5]
 [3.  1.5 4. ]]
S == S.T : True


### Determinante, traza, rango e inversa

**Determinante** $\det(A)$ — sólo para matrices **cuadradas**. Para una matriz $2\times 2$ se calcula así:

$$
\det\begin{bmatrix} a & b \\ c & d\end{bmatrix} = ad - bc
$$

**Traza** $\operatorname{tr}(A) = \sum_{i=1}^{n} a_{ii}$ — la suma de la diagonal.

**Rango** $\operatorname{rank}(A)$ — cantidad de filas o columnas que aportan información no repetida.

**Inversa** $A^{-1}$ — la matriz que permite deshacer un producto por $A$ cuando existe. Para el caso $2\times 2$:

$$
A^{-1} = \frac{1}{ad-bc}\begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

En problemas simples, estas herramientas sirven para saber si un sistema tiene solución única y para resolver ecuaciones con varias incógnitas.

> Si $\det(A) = 0$, la matriz es **singular** y no tiene inversa.


In [106]:
import numpy as np

A = np.array([[4., 7.], [2., 6.]])
B = np.array([[1., 2.], [3., 5.]])
alpha = 3.0

print("A =")
print(A)
print(f"\ndet(A) = {np.linalg.det(A):.4f}   (a*d - b*c = 4*6 - 7*2 = {4*6 - 7*2})")
print(f"tr(A)  = {np.trace(A):.4f}")
print(f"rank(A) = {np.linalg.matrix_rank(A)}")

print("\ninversa A^-1 =")
print(np.linalg.inv(A))
print(f"\nA @ A^-1 == I : {np.allclose(A @ np.linalg.inv(A), np.eye(2))}")

print("\n--- propiedades practicas ---")
print(f"det(A^T) == det(A)          : {np.isclose(np.linalg.det(A.T), np.linalg.det(A))}")
print(f"det(AB) == det(A)det(B)     : {np.isclose(np.linalg.det(A @ B), np.linalg.det(A) * np.linalg.det(B))}")
print(f"det(aA) == a^2 det(A)       : {np.isclose(np.linalg.det(alpha * A), alpha**2 * np.linalg.det(A))}")
print(f"tr(A+B) == tr(A)+tr(B)      : {np.isclose(np.trace(A + B), np.trace(A) + np.trace(B))}")
print(f"(AB)^-1 == B^-1 A^-1        : {np.allclose(np.linalg.inv(A @ B), np.linalg.inv(B) @ np.linalg.inv(A))}")


A =
[[4. 7.]
 [2. 6.]]

det(A) = 10.0000   (a*d - b*c = 4*6 - 7*2 = 10)
tr(A)  = 10.0000
rank(A) = 2

inversa A^-1 =
[[ 0.6 -0.7]
 [-0.2  0.4]]

A @ A^-1 == I : True

--- propiedades practicas ---
det(A^T) == det(A)          : True
det(AB) == det(A)det(B)     : True
det(aA) == a^2 det(A)       : True
tr(A+B) == tr(A)+tr(B)      : True
(AB)^-1 == B^-1 A^-1        : True


In [107]:
import numpy as np

# --- matriz SINGULAR: la fila 2 es el doble de la fila 1 ---
S = np.array([[1., 2., 3.],
              [2., 4., 6.],
              [1., 1., 1.]])

print("matriz S (fila 2 = 2 x fila 1):")
print(S)
print(f"\ndet(S)   = {np.linalg.det(S):.10f}   -> practicamente 0")
print(f"rank(S)  = {np.linalg.matrix_rank(S)}   de un maximo de {min(S.shape)}  -> deficiente en rango")

try:
    np.linalg.inv(S)
except np.linalg.LinAlgError as e:
    print(f"\nnp.linalg.inv(S) falla: {e}")

# el sistema homogeneo Sx = 0 tiene soluciones no triviales
print("\n--- comparacion de rangos ---")
for nombre, M in {
    "identidad 3x3": np.eye(3),
    "singular S": S,
    "matriz 3x5 aleatoria": np.random.default_rng(7).normal(size=(3, 5)),
    "producto columna x fila": np.outer([1., 2., 3.], [4., 5., 6.]),
}.items():
    print(f"{nombre:<25} shape={str(M.shape):<8} rank={np.linalg.matrix_rank(M)}")

matriz S (fila 2 = 2 x fila 1):
[[1. 2. 3.]
 [2. 4. 6.]
 [1. 1. 1.]]

det(S)   = 0.0000000000   -> practicamente 0
rank(S)  = 2   de un maximo de 3  -> deficiente en rango

np.linalg.inv(S) falla: Singular matrix

--- comparacion de rangos ---
identidad 3x3             shape=(3, 3)   rank=3
singular S                shape=(3, 3)   rank=2
matriz 3x5 aleatoria      shape=(3, 5)   rank=3
producto columna x fila   shape=(3, 3)   rank=1


## Broadcasting

Broadcasting permite operar entre arrays de **distinta forma** sin copiar datos.
La regla básica: NumPy "expande" el array más pequeño para que las formas sean compatibles.

<img src="https://raw.githubusercontent.com/fralfaro/MAT281_2022/main/docs/lectures/data_manipulation/scientific_computing/images/broad.png" width = "500" align="center"/>



### Escalar con vector

Cuando operamos un escalar con un vector, NumPy aplica el escalar a cada elemento del vector.


In [108]:
import numpy as np

print("escalar + vector (np.arange(3) + 5):")
print(np.arange(3) + 5)


escalar + vector (np.arange(3) + 5):
[5 6 7]


In [109]:
import numpy as np

print("escalar * vector (np.arange(3) * 3):")
print(np.arange(3) * 3)


escalar * vector (np.arange(3) * 3):
[0 3 6]


### Matriz con vector por filas

Si una matriz tiene forma `(3, 3)` y el vector tiene forma `(3,)`, NumPy puede repetir el vector en cada fila para hacer la operación.


In [110]:
import numpy as np

print("matriz ones(3,3) + arange(3):")
print(np.ones((3, 3)) + np.arange(3))


matriz ones(3,3) + arange(3):
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [111]:
import numpy as np

print("matriz ones(3,3) * arange(3):")
print(np.ones((3, 3)) * np.arange(3))


matriz ones(3,3) * arange(3):
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


### Vector columna con vector fila

Un vector columna de forma `(3, 1)` y un vector fila de forma `(3,)` se expanden para formar una matriz `(3, 3)`.


In [112]:
import numpy as np

col = np.arange(3).reshape((3, 1))
fil = np.arange(3)

print("columna:")
print(col)
print("\nfila:")
print(fil)
print("\nresultado col + fila:")
print(col + fil)


columna:
[[0]
 [1]
 [2]]

fila:
[0 1 2]

resultado col + fila:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


### Comparaciones y filtrado

El broadcasting también aparece en comparaciones. El resultado de una comparación es un array de valores booleanos (`True` o `False`), que luego puede usarse para filtrar.


In [113]:
import numpy as np

M = np.arange(9).reshape((3, 3))

print("matriz M:")
print(M)
print("\nM > 4:")
print(M > 4)
print("\nM[M > 4]  (filtrado):")
print(M[M > 4])


matriz M:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

M > 4:
[[False False False]
 [False False  True]
 [ True  True  True]]

M[M > 4]  (filtrado):
[5 6 7 8]


### Operaciones con shapes compatibles

En este ejemplo, `A` tiene forma `(3, 3)` y `b` tiene forma `(3,)`. NumPy divide cada fila de `A` por el vector `b`.


In [114]:
import numpy as np

A = np.ones((3, 3)) * 10
b = np.array([1, 2, 3])

print("A (3x3):")
print(A)
print("\nb (3,):")
print(b)
print("\nA / b:")
print(A / b)


A (3x3):
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]

b (3,):
[1 2 3]

A / b:
[[10.          5.          3.33333333]
 [10.          5.          3.33333333]
 [10.          5.          3.33333333]]


## Resumen: notación matemática ↔ NumPy

| Concepto | Notación | NumPy |
|---|---|---|
| Vector de $\mathbb{R}^n$ | $\mathbf{v}$ | `np.array([...])`, `shape=(n,)` |
| Matriz $m\times n$ | $A$ | `np.array([[...]])`, `shape=(m, n)` |
| Elemento | $a_{ij}$ | `A[i-1, j-1]` |
| Suma | $A + B$ | `A + B` |
| Producto por escalar | $\alpha A$ | `alpha * A` |
| Producto elemento a elemento | $A \odot B$ | `A * B` |
| Producto punto | $\mathbf{u}\cdot\mathbf{v}$ | `u @ v`, `np.dot(u, v)` |
| Producto matricial | $AB$ | `A @ B`, `np.matmul(A, B)` |
| Transpuesta | $A^{T}$ | `A.T` |
| Norma euclidiana | $\|\mathbf{v}\|_2$ | `np.linalg.norm(v)` |
| Identidad | $I_n$ | `np.eye(n)` |
| Diagonal | $\operatorname{diag}(\mathbf{v})$ | `np.diag(v)` |
| Traza | $\operatorname{tr}(A)$ | `np.trace(A)` |
| Determinante | $\det(A)$ | `np.linalg.det(A)` |
| Rango | $\operatorname{rank}(A)$ | `np.linalg.matrix_rank(A)` |
| Inversa | $A^{-1}$ | `np.linalg.inv(A)` |
| Sistema lineal | $A\mathbf{x}=\mathbf{b}$ | `np.linalg.solve(A, b)` |
| Mínimos cuadrados | $\min\|A\mathbf{x}-\mathbf{b}\|^2$ | `np.linalg.lstsq(A, b)` |

**Errores frecuentes:**

1. Confundir `A * B` con `A @ B`.
2. Asumir que $AB = BA$; el producto matricial no siempre conmuta.
3. Intentar multiplicar matrices cuyas dimensiones internas no coinciden.
4. Usar `inv(A) @ b` en vez de `solve(A, b)` para resolver sistemas.
5. Olvidar que un vector 1D de NumPy (`shape=(n,)`) no es fila ni columna.


## Referencias

1. [Quickstart tutorial-numpy](https://docs.scipy.org/doc/numpy/user/quickstart.html)
